INSERT INTO EMPLOYEE VALUES(1,'NANI@GMAIL.COM','TANSI','KODAM');
INSERT INTO EMPLOYEE VALUES(2,'NIKHI@GMAIL.COM','BABY','KODAM');
INSERT INTO EMPLOYEE VALUES(3,'POSTMAN@GMAIL.COM','NIKHILA','KODAM');
INSERT INTO EMPLOYEE VALUES(4,'AADVI@GMAIL.COM','AADVI','OMI');
